[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 18_000
evm_version="Istanbul"
no_match_path = "contracts/*"
rpc_endpoints = { mainnet = "https://api.harmony.one" }
remappings = [
    '@uniswap/v2-core/contracts/=lib/v2-core/contracts/',
    '@uniswap/v3-core/contracts/=lib/v3-core/contracts/',
    '@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts/',
    '@contracts/=contracts/',
    '@prb/math/=lib/prb-math/'
]

[profile.local]
rpc_endpoints = { mainnet = "http://127.0.0.1:8545" }